# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-05 07:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='martist',
            name='art_update',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='mdetail',
            name='m_actor',
            field=models.CharField(default='无', max_length=500),
        ),
        migrations.AddField(
            model_name='mdetail',
            name='m_director',
            field=models.CharField(default='无', max_length=100),
        ),
        migrations.AddField(
            model_name='mdetail',
            name='m_writer',
            field=models.CharField(default='无', max_length=100),
        ),
        migrations.AlterField(
            model_name='mdetail',
            name='m_imdb_serial',
            field=models.CharField(default='无', max_length=100),
        ),
    ]
