# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-05 08:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_auto_20170605_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mdetail',
            name='m_area',
            field=models.ManyToManyField(related_name='m_id', to='movie.Marea'),
        ),
        migrations.AlterField(
            model_name='mdetail',
            name='m_tag',
            field=models.ManyToManyField(related_name='m_id', to='movie.Mtag'),
        ),
    ]
